/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ReferRouteImport } from './routes/refer'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as MortgagesRouteImport } from './routes/mortgages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BookRouteImport } from './routes/book'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PortalInformationFormRouteImport } from './routes/portal.information-form'
import { Route as PortalDocumentsRouteImport } from './routes/portal.documents'
import { Route as AdminCasesCaseIdRouteImport } from './routes/admin.cases.$caseId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferRoute = ReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const MortgagesRoute = MortgagesRouteImport.update({
  id: '/mortgages',
  path: '/mortgages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PortalInformationFormRoute = PortalInformationFormRouteImport.update({
  id: '/information-form',
  path: '/information-form',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRoute,
} as any)
const AdminCasesCaseIdRoute = AdminCasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/book': typeof BookRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/compliance': typeof ComplianceRoute
  '/insurance': typeof InsuranceRoute
  '/login': typeof LoginRoute
  '/mortgages': typeof MortgagesRoute
  '/portal': typeof PortalRouteWithChildren
  '/refer': typeof ReferRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/information-form': typeof PortalInformationFormRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/cases/$caseId': typeof AdminCasesCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/book': typeof BookRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/compliance': typeof ComplianceRoute
  '/insurance': typeof InsuranceRoute
  '/login': typeof LoginRoute
  '/mortgages': typeof MortgagesRoute
  '/refer': typeof ReferRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/information-form': typeof PortalInformationFormRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/admin/cases/$caseId': typeof AdminCasesCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/book': typeof BookRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/compliance': typeof ComplianceRoute
  '/insurance': typeof InsuranceRoute
  '/login': typeof LoginRoute
  '/mortgages': typeof MortgagesRoute
  '/portal': typeof PortalRouteWithChildren
  '/refer': typeof ReferRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/information-form': typeof PortalInformationFormRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/cases/$caseId': typeof AdminCasesCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/apply'
    | '/book'
    | '/chat'
    | '/compare'
    | '/compliance'
    | '/insurance'
    | '/login'
    | '/mortgages'
    | '/portal'
    | '/refer'
    | '/resources'
    | '/signup'
    | '/sitemap.xml'
    | '/portal/documents'
    | '/portal/information-form'
    | '/admin/'
    | '/portal/'
    | '/admin/cases/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apply'
    | '/book'
    | '/chat'
    | '/compare'
    | '/compliance'
    | '/insurance'
    | '/login'
    | '/mortgages'
    | '/refer'
    | '/resources'
    | '/signup'
    | '/sitemap.xml'
    | '/portal/documents'
    | '/portal/information-form'
    | '/admin'
    | '/portal'
    | '/admin/cases/$caseId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/apply'
    | '/book'
    | '/chat'
    | '/compare'
    | '/compliance'
    | '/insurance'
    | '/login'
    | '/mortgages'
    | '/portal'
    | '/refer'
    | '/resources'
    | '/signup'
    | '/sitemap.xml'
    | '/portal/documents'
    | '/portal/information-form'
    | '/admin/'
    | '/portal/'
    | '/admin/cases/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  BookRoute: typeof BookRoute
  ChatRoute: typeof ChatRoute
  CompareRoute: typeof CompareRoute
  ComplianceRoute: typeof ComplianceRoute
  InsuranceRoute: typeof InsuranceRoute
  LoginRoute: typeof LoginRoute
  MortgagesRoute: typeof MortgagesRoute
  PortalRoute: typeof PortalRouteWithChildren
  ReferRoute: typeof ReferRoute
  ResourcesRoute: typeof ResourcesRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer': {
      id: '/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof ReferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mortgages': {
      id: '/mortgages'
      path: '/mortgages'
      fullPath: '/mortgages'
      preLoaderRoute: typeof MortgagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/portal/information-form': {
      id: '/portal/information-form'
      path: '/information-form'
      fullPath: '/portal/information-form'
      preLoaderRoute: typeof PortalInformationFormRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documents': {
      id: '/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/cases/$caseId': {
      id: '/admin/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/admin/cases/$caseId'
      preLoaderRoute: typeof AdminCasesCaseIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCasesCaseIdRoute: typeof AdminCasesCaseIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCasesCaseIdRoute: AdminCasesCaseIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalRouteChildren {
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalInformationFormRoute: typeof PortalInformationFormRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalInformationFormRoute: PortalInformationFormRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ApplyRoute: ApplyRoute,
  BookRoute: BookRoute,
  ChatRoute: ChatRoute,
  CompareRoute: CompareRoute,
  ComplianceRoute: ComplianceRoute,
  InsuranceRoute: InsuranceRoute,
  LoginRoute: LoginRoute,
  MortgagesRoute: MortgagesRoute,
  PortalRoute: PortalRouteWithChildren,
  ReferRoute: ReferRoute,
  ResourcesRoute: ResourcesRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
